# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f72f428c7773b78bb4aec519945fe11ccd2eda608b77fc12dfb69fe1cea410e80714387054e3691a66f2ddf524f57f66b75de00f2dfd2bc6e637f8c871873bf

test:
  secret_key_base: 3691af991b9de67dc40a536138374e8d06303ed0787d9db41fbf350d19df22890d516b057739936fed1dcca33c763da6b838f6db782354738ebd84806f7ecd82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
